### ISSUE TITLE
Suggestion for UI of warfare unit cards

### ISSUE THREAD

**Issue by bhi-elliot** [JPMeehan/knw-actors#11]
Hi!
Thanks so much for this module. It's great already!
I don't know if this will help you, but I've been using one I slightly modified from someone else who made one a long time ago for Strongholds & Followers. I took what they made and added the 'Command' roll from Kingdoms & Warfare.

The layout of the cards is a bit cleaner and more consistent with what's found in those books. I particular like the dark mode.

Feel free to use whatever.

https://github.com/bhi-elliot/warfare-with-command

**Comment by JPMeehan** [comment]
I think I'm happy with the current layout; the goal here was K&W, rather than S&F, warfare units.
