### ISSUE TITLE
Levies graphic broken

### ISSUE THREAD

**Issue by bhi-elliot** [JPMeehan/knw-actors#17]
When selecting Levy on the warfare unit sheet, graphic to the left shows a broken link.
<img width="100" alt="Screenshot 2024-02-02 001716" src="https://github.com/JPMeehan/knw-actors/assets/5731653/2d68509d-d3f1-47d5-b547-cf2c92761f0c">

**Comment by JPMeehan** [comment]
Oops forgot to include in the assets. Fixed in upcoming version.
