### ISSUE TITLE
Token Resource Attirbutes not available

### ISSUE THREAD

**Issue by bhi-elliot** [JPMeehan/knw-actors#18]
If we want to display, for example, the casualities (hp) of the unit on the token as a display bar, there does not seem to be the option.
<img width="354" alt="Screenshot 2024-02-02 001936" src="https://github.com/JPMeehan/knw-actors/assets/5731653/cfc1a581-5603-4341-be93-42c43d903b0a">

**Comment by JPMeehan** [comment]
This is a bug introduced by dnd5e 3.0, I missed that in their updates to the TokenConfig they kinda broke things.
