### ISSUE TITLE
Long title "active effects" on warfare units does not display properly

### ISSUE THREAD

**Issue by bhi-elliot** [JPMeehan/knw-actors#19]
It pushes some of the interface down quite far unless you expand the window quite a lot. Even then, it doesn't show the whole title.
<img width="462" alt="Screenshot 2024-02-05 001359" src="https://github.com/JPMeehan/knw-actors/assets/5731653/e438c34a-4e65-4363-b081-51ab5c74deab">

**Comment by JPMeehan** [comment]
You should be using the Description field, rather than putting everything in the name.

**Comment by bhi-elliot** [comment]
But the Description field does not show up anywhere, correct?
Also, the 'Edit Effect' button conflicts with module 'Dynamic effects using Active Effects (DAE)', so that nothing happens when you click the button.

**Comment by JPMeehan** [comment]
What error shows up in console with DAE?

**Comment by bhi-elliot** [comment]
Dunno if this helps:
```
DevTools failed to load source map: Could not load content for http://localhost:31253/modules/knw-actors/knw-actors.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

foundry.js:5802 Foundry VTT | Rendering WarfareSheet
DAEActiveEffectConfig.js:38 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'allSpecsObj')
[Detected 2 packages: dae, knw-actors]
    at new DAEActiveEffectConfig (DAEActiveEffectConfig.js:38:55)
    at get sheet [as sheet] (foundry.js:14122:23)
    at #handleEmbeddedDocumentControl (knw-actors.mjs:1082:13)
    at HTMLFormElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
DAEActiveEffectConfig | @ | DAEActiveEffectConfig.js:38
-- | -- | --
  | get sheet | @ | foundry.js:14122
  | #handleEmbeddedDocumentControl | @ | knw-actors.mjs:1082
  | dispatch | @ | jquery.min.js:2
  | y.handle | @ | jquery.min.js:2
```

**Comment by JPMeehan** [comment]
That's DAE not accounting for module subtypes. File a bug with that module: https://gitlab.com/tposney/dae/-/issues

**Comment by JPMeehan** [comment]
As for the description field, it's visible in the edit page, but I'll throw it in as a dropout like the old dnd5e sheet
