### ISSUE TITLE
Cannot Modify warfare Units Sheet

### ISSUE THREAD

**Issue by Bfavilla** [JPMeehan/knw-actors#21]
![image](https://github.com/JPMeehan/knw-actors/assets/45344025/31ee6989-dcbd-4294-a41f-690b79641e72)
I can create warfare units and add a commander to it, but I cant add modifiers to the unit or edit the stats

**Comment by JPMeehan** [comment]
One or more of your modules are interfering.

**Comment by Bfavilla** [comment]
Yup, found the incompatibility with another warfare module I was testing.
Thank you for the fast response
