### ISSUE TITLE
Dice don't roll when using warfare units

### ISSUE THREAD

**Issue by Jagstir** [JPMeehan/knw-actors#22]
When rolling attack rolls and other rollable stats like power, the dice roll does not go off. This happens regardless if an actor is assigned to the warfare unit. Rolling stats on the organization sheets still work as normal.

Here is an image of the error message that pops up in console:

![image](https://github.com/JPMeehan/knw-actors/assets/166970848/769046b6-3b56-4dd7-956b-73964e418584)

**Comment by JPMeehan** [comment]
1. What version of the module are you on?
2. What other modules do you have?

**Comment by Jagstir** [comment]
Version is 1.2.1

Module list is here (hope the images are readable):
![image](https://github.com/JPMeehan/knw-actors/assets/166970848/5069bf29-133e-43f6-af45-0b55d2f4efb0)
![image](https://github.com/JPMeehan/knw-actors/assets/166970848/fe0b6ea9-9a06-4156-9722-9a332709a098)

**Comment by JPMeehan** [comment]
these are all active? you can filter to active modules in a world by going to the Module Management menu and clicking the tab
![image](https://github.com/JPMeehan/knw-actors/assets/16617088/db095bcf-4f4d-45e4-954d-ede31220ceb5)

**Comment by Jagstir** [comment]
Oop sorry. Here's a more accurate list including active modules. 

![image](https://github.com/JPMeehan/knw-actors/assets/166970848/96cf7cf4-1f6a-47f3-bc6f-e857cbb4892b)

![image](https://github.com/JPMeehan/knw-actors/assets/166970848/8450c260-51a9-4e21-b795-ebe2d4f70818)

**Comment by JPMeehan** [comment]
Oh oops somehow a typo that got unnoticed for weeks. Fixed in upcoming release.
