### ISSUE TITLE
Defense Levels should not be affecting Defense Score

### ISSUE THREAD

**Issue by bhi-elliot** [JPMeehan/knw-actors#23]
Hello,
This was a point of confusion for me as well, but I've just had it confirmed through MCDM's Discord.
If a Defense _Level_ is raised, it doesn't affect the Defense _Score_.

For example, the Domain Action called Like in the Great Stories for the Adventuring Party raising the Resolve _Level_ by two. In your module, when I take the Rosolve to 'Fanatic' from 'Normal' (which is how one would indicate that the Level is increased by 2), the Resolve score also increases by 2, but this is incorrect. The score should remain the same.

Hopefully this makes sense. It is confusing that they used the same word (ex. Resolve) to indicate both a Score and a Level, which are independent.

Thank you.

**Comment by JPMeehan** [comment]
Reading through the conversation - the stats on the sheet reflect what you'd use in battle; the configuration menu helps track the underlying score independent of the level. So the Great Stories would give that effective +2 bonus.

**Comment by bhi-elliot** [comment]
Hmmm... I don't think that's how it's supposed to work. They are completely different scales. The Great Stories Feature just makes it so a hero can cast a spell or make an attack (Resolve is set to Fanatic). It has nothing to do with putting +2 anywhere in a roll.

The Levels go -3 to +3 and Score is 10 and up.
And I don't think they effect one another.

For example, if an opposing faction makes a test against a Defense, they should be making it against the Score, not the Score + Level. I can't find any example of when you'd want to know the Score plus the Level.

The Level is only for determining special starting circumstances for battles or warfare (such as Cavalry having disadvantage on the first round, or the example about with the Great Stories).

**Comment by JPMeehan** [comment]
Okay, I definitely misread the rules and what the levels are for.

**Comment by bhi-elliot** [comment]
I did too at first. The fact that they use the same name for Score and Level makes it really confusing.
'Communication Score' and 'Communication Level' sound very very similar.
